"""add_step_outcomes_to_pipeline_runs

Revision ID: 7b2ec1319045
Revises: ef5a6f0d3bdd
Create Date: 2026-07-01 19:30:46.472174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b2ec1319045'
down_revision: Union[str, None] = 'ef5a6f0d3bdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_runs', sa.Column('step_outcomes', sa.JSON(), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_runs', 'step_outcomes')
    # ### end Alembic commands ###
