"""create_initial_tables

Revision ID: b978f505f4cf
Revises: d4b8e2a9f1c3
Create Date: 2026-06-12 20:03:21.375486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'b978f505f4cf'
down_revision: Union[str, None] = 'd4b8e2a9f1c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_url', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('post_url', sa.String(length=500), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_raw_posts_source_external_id')
    )
    op.create_index('ix_raw_posts_published_at', 'raw_posts', ['published_at'], unique=False)
    op.create_index('ix_raw_posts_source', 'raw_posts', ['source'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('preferred_contract_type', sa.String(length=50), nullable=False),
    sa.Column('target_tjm', sa.Float(), nullable=False),
    sa.Column('preferred_remote_mode', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('availability', sa.DateTime(timezone=True), nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', Vector(384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_user_profiles_email')
    )
    op.create_index('ix_user_profiles_availability', 'user_profiles', ['availability'], unique=False)
    op.create_index('ix_user_profiles_email', 'user_profiles', ['email'], unique=False)
    op.create_index('ix_user_profiles_preferred_contract_type', 'user_profiles', ['preferred_contract_type'], unique=False)
    op.create_table('analyzed_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_post_id', sa.UUID(), nullable=False),
    sa.Column('is_mission', sa.Boolean(), nullable=False),
    sa.Column('detected_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detected_tjm_amount', sa.Float(), nullable=True),
    sa.Column('detected_contract_type', sa.String(length=50), nullable=False),
    sa.Column('detected_remote_mode', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('analysis_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raw_post_id'], ['raw_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analyzed_posts_confidence_score', 'analyzed_posts', ['confidence_score'], unique=False)
    op.create_index('ix_analyzed_posts_is_mission', 'analyzed_posts', ['is_mission'], unique=False)
    op.create_table('mission_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_profile_id', sa.UUID(), nullable=False),
    sa.Column('analyzed_post_id', sa.UUID(), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=False),
    sa.Column('stack_score', sa.Float(), nullable=False),
    sa.Column('contract_score', sa.Float(), nullable=False),
    sa.Column('tjm_score', sa.Float(), nullable=False),
    sa.Column('remote_score', sa.Float(), nullable=False),
    sa.Column('global_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analyzed_post_id'], ['analyzed_posts.id'], ),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_profile_id', 'analyzed_post_id', name='uq_mission_match')
    )
    op.create_index('ix_mission_matches_analyzed_post_id', 'mission_matches', ['analyzed_post_id'], unique=False)
    op.create_index('ix_mission_matches_global_score', 'mission_matches', ['global_score'], unique=False)
    op.create_index('ix_mission_matches_user_profile_id', 'mission_matches', ['user_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mission_matches_user_profile_id', table_name='mission_matches')
    op.drop_index('ix_mission_matches_global_score', table_name='mission_matches')
    op.drop_index('ix_mission_matches_analyzed_post_id', table_name='mission_matches')
    op.drop_table('mission_matches')
    op.drop_index('ix_analyzed_posts_is_mission', table_name='analyzed_posts')
    op.drop_index('ix_analyzed_posts_confidence_score', table_name='analyzed_posts')
    op.drop_table('analyzed_posts')
    op.drop_index('ix_user_profiles_preferred_contract_type', table_name='user_profiles')
    op.drop_index('ix_user_profiles_email', table_name='user_profiles')
    op.drop_index('ix_user_profiles_availability', table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index('ix_raw_posts_source', table_name='raw_posts')
    op.drop_index('ix_raw_posts_published_at', table_name='raw_posts')
    op.drop_table('raw_posts')
    # ### end Alembic commands ###
