"""add_cv_raw_text_to_user_profiles

Revision ID: 3a60da7c9068
Revises: b978f505f4cf
Create Date: 2026-06-14 08:25:00.190475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a60da7c9068'
down_revision: Union[str, None] = 'b978f505f4cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('cv_raw_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'cv_raw_text')
    # ### end Alembic commands ###
